<?php
?> 
    <h1><?php echo $this->escapeHtml($this->title); ?></h1>
    <?php
    $form = $this->formulario;
//    $form->setAttribute('action', $this->url('auth', array('action' => 'add')));
    $form->prepare();
    ?>
    <div flex-sm="100" flex-gt-sm="80" layout-sm="column" >
        <?php echo $this->form()->openTag($form); ?>
        <md-input-container class="md-block">
            <label>Usuario </label>
            <?php echo $this->formInput($form->get('user')); ?>
        </md-input-container>
        <md-input-container class="md-block">
            <label>Contraseña </label>
            <?php echo $this->formInput($form->get('pass')); ?>
        </md-input-container>
        <?php
//        echo $this->formSubmit($form->get('entrar'));
        ?>

        <md-button class="md-raised md-primary" type="submit">Entrar</md-button>
        <?php echo $this->form()->closeTag() ?>
    </div>
