<?php echo $this->doctype(); ?>
<html lang="es">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('GP ' . $this->translate('Comprass'))->setSeparator(' - ')->setAutoEscape(false) ?>
        <?php
        echo $this->headMeta()
                ->appendName('viewport', 'width=device-width, initial-scale=1.0')
                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>
        <!-- style sheet -->
        <?php
        echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/logo.png'))
                ->prependStylesheet($this->basePath('css/angular-material.min.css'))
        ?>
        <!-- header script -->
        <?php
        echo $this->headScript()
                ->prependFile($this->basePath('js/angular.min.js'))
        ; ?>
    </head>
    <style type="text/css">
        footer {
            position : absolute;
            bottom : 0;
            left:0;
            right:0;
            margin-left:auto;
            margin-right:auto;
            width: 95%;
            text-align: right;
        }
    </style>
    <script type="text/javascript">
        var basePath = "<?php echo $this->basePath(); ?>";
    </script>
    <body>
        <div ng-app="ToolBar">
            <md-toolbar  class="md-menu-toolbar">
                <div layout="row">
                    <md-toolbar-filler layout layout-align="center center">
                        <!--<md-icon md-svg-icon="call:chat"></md-icon>-->
                    </md-toolbar-filler>
                    <div>
                        <h2 class="md-toolbar-tools">Comprass</h2>
                        <md-menu-bar ng-controller="MenuCtrl as ctrl" ng-cloak id="menu-bar">
                            <md-menu>
                                <button ng-click="ctrl.redirectAction('home')">
                                    Inicio
                                </button>
                                <md-menu-content>
                                    <md-menu-item>
                                        <md-button >
                                            Inicio
                                        </md-button>
                                    </md-menu-item>
                                </md-menu-content>
                            </md-menu>
                        </md-menu-bar>
                    </div>
                </div>
            </md-toolbar>
        </div>

            <?php echo $this->navigation('navigation')->menu(); ?>

<!--        <md-toolbar layout="row" >
            <h6>Comprass - Starter App</h6>
            <?php //echo $this->navigation()->breadcrumbs(); ?>
            <?php //echo $this->navigation()->breadcrumbs()->render(); ?>
        </md-toolbar>-->
        <md-content flex id="content">
            <?php echo $this->content; ?>
        </md-content>
        <footer>
            <hr>
            <p>&copy; 2016 - <?php echo date('Y') ?> by Grupo Promass. <?php echo $this->translate('All rights reserved.') ?></p>
        </footer>
        <!-- inline script -->
        <?php echo $this->inlineScript() 
            ->prependFile($this->basePath('js/angular-animate.min.js'))
            ->prependFile($this->basePath('js/angular-aria.min.js'))
            ->prependFile($this->basePath('js/angular-messages.min.js'))
            ->prependFile($this->basePath('js/angular-material.min.js'))
            ->prependFile($this->basePath('js/menu.js'))
        ; ?>
    </body>
</html>

