<?php echo $this->doctype(); ?>
<html lang="en" >
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('GP ' . $this->translate('Comprass'))->setSeparator(' - ')->setAutoEscape(false) ?>
        <?php
        echo $this->headMeta()
                ->appendName('viewport', 'width=device-width, initial-scale=1.0')
                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>
        <!-- style sheet -->
        <?php
        echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/logo.png'))
                ->prependStylesheet($this->basePath('css/angular-material.min.css'))
        ?>
        <!--<link rel="stylesheet" href="http://ajax.googleapis.com/ajax/libs/angular_material/1.0.0/angular-material.min.css">-->
        <?php
        echo $this->headScript()
                ->prependFile($this->basePath('js/angular.min.js'))
        ; ?>
    </head>

    <body ng-app="ComprassApp" >
        <!--
          Your HTML content here
        -->  
        <div flex layout="row">
            <!-- Container #4 -->
            <md-content flex id="content">
                <?php echo $this->content; ?>
                    <div flex-sm="100" flex-gt-sm="80" layout-sm="column">
                        <form name="contactForm" data-ng-submit="sendMail()">
                            <md-input-container>
                                <label>Name:</label>
                                <input ng-model="contactName" required>
                            </md-input-container>
                            <md-input-container flex>
                                <label>Email:</label>
                                <input type="email" ng-model="contactEmail" required>
                            </md-input-container>

                            <md-input-container>
                                <label>Message:</label>
                                <textarea ng-model="contactMsg" columns="1" md-maxlength="150" required></textarea>
                            </md-input-container>

                            <md-button type="submit" class="md-primary"
                                       ng-class="{'md-raised md-hue-1': (contactForm.$dirty && contactForm.$valid) }"
                                       aria-label="Save Project">Send</md-button>
                        </form>
                    </div>
                <hr>
                <footer>
                    <p>&copy; 2016 - <?php echo date('Y') ?> by Grupo Promass. <?php echo $this->translate('All rights reserved.') ?></p>
                </footer>
            </md-content>

        </div>

        <!-- inline script -->
        <?php echo $this->inlineScript() 
            ->prependFile($this->basePath('js/angular-animate.min.js'))
            ->prependFile($this->basePath('js/angular-aria.min.js'))
            ->prependFile($this->basePath('js/angular-messages.min.js'))
            ->prependFile($this->basePath('js/angular-material.min.js'))
        ; ?>

        <!-- Angular Material requires Angular.js Libraries -->
        <!--<script src="http://ajax.googleapis.com/ajax/libs/angularjs/1.4.8/angular.min.js"></script>-->
<!--        <script src="http://ajax.googleapis.com/ajax/libs/angularjs/1.4.8/angular-animate.min.js"></script>
        <script src="http://ajax.googleapis.com/ajax/libs/angularjs/1.4.8/angular-aria.min.js"></script>
        <script src="http://ajax.googleapis.com/ajax/libs/angularjs/1.4.8/angular-messages.min.js"></script>

         Angular Material Library 
        <script src="http://ajax.googleapis.com/ajax/libs/angular_material/1.0.0/angular-material.min.js"></script>-->

        <!-- Your application bootstrap  -->
        <script type="text/javascript">
                                         /**
                                          * You must include the dependency on 'ngMaterial' 
                                          */
//                                         angular.module('ComprassApp', ['ngMaterial']);

            Comprass = angular.module('ComprassApp', ['ngMaterial'])
            .config(function($mdThemingProvider) {
              $mdThemingProvider.theme('default')
                .primaryPalette('blue',{'default': '900'})
                .accentPalette('light-blue');
            });
        </script>

    </body>
</html>

<!--
Copyright 2016 Google Inc. All Rights Reserved. 
Use of this source code is governed by an MIT-style license that can be in foundin the LICENSE file at http://material.angularjs.org/license.
-->

