<?php echo $this->doctype(); ?>
<html ng-app="comprass">
    <head>
        <script src="/comprass/public/js/angular.min.js"></script>
        <link rel="stylesheet" href="/comprass/public/css/ui-grid.min.css">
        <link rel="stylesheet" href="/comprass/public/css/angular-material.min.css">
    </head>
    <style>
        .grid {
            width: 500px;
            height: 250px;
        }
    </style>
    <script type="text/javascript">
        var basePath = "<?php echo $this->basePath(); ?>";
    </script>
    <body >
        <div ng-module="ToolBar">
            <md-toolbar  class="md-menu-toolbar">
                <div layout="row">
                    <md-toolbar-filler layout layout-align="center center">
                        <!--<md-icon md-svg-icon="call:chat"></md-icon>-->
                    </md-toolbar-filler>
                    <div>
                        <h2 class="md-toolbar-tools">Comprass</h2>
                        <md-menu-bar ng-controller="MenuCtrl as ctrl" ng-cloak id="menu-bar">
                            <md-menu>
                                <button ng-click="ctrl.redirectAction('home')">
                                    Inicio
                                </button>
                                <md-menu-content>
                                    <md-menu-item>
                                        <md-button >
                                            Inicio
                                        </md-button>
                                    </md-menu-item>
                                </md-menu-content>
                            </md-menu>
                        </md-menu-bar>
                    </div>
                </div>
            </md-toolbar>
        </div>
        <div ng-module="app">
            <div ng-controller="MainCtrl">
                <div id="grid1" ui-grid="{ data: myData }" class="grid"></div>
            </div>
        </div>
        <?php echo $this->navigation('navigation')->menu(); ?>
            <script src="/comprass/public/js/ui-grid.min.js"></script>
            <script src="/comprass/public/js/angular-touch.js"></script>
            <script src="/comprass/public/js/angular-animate.min.js"></script>
            <script src="/comprass/public/js/angular-aria.min.js"></script>
            <script src="/comprass/public/js/angular-messages.min.js"></script>
            <script src="/comprass/public/js/angular-material.min.js"></script>
            <script src="/comprass/public/js/menu.js"></script>
            <script src="/comprass/public/js/module/capacidades/index.js"></script>
<!--        <script src="http://ui-grid.info/docs/grunt-scripts/csv.js"></script>
        <script src="http://ui-grid.info/docs/grunt-scripts/pdfmake.js"></script>-->
        <!--<script src="http://ui-grid.info/docs/grunt-scripts/vfs_fonts.js"></script>-->
    </body>
</html>

